### ISSUE TITLE
Possible future build tools

### ISSUE THREAD

**Issue by Adamek-K** [Adamek-K/feather-engine#1]
The project has been migrated over to **SCons**. I am leaving this open for discussion.

**Comment by prestonf136** [comment]
I'd love to work at this project but alas, it does not compile!, I'd suggest SCons, but I don't believe you can go wrong with either.

**Comment by Adamek-K** [comment]
hey, thanks yeah i have been having some issues compiling it too. it worked fine before, but ever since @BoogeyMan24 introduced the libs and include into the project it has been failing to compile. i am working on getting a fix ASAP. thanks for your interest in the project :)

**Comment by Adamek-K** [comment]
@prestonf136 the project has been migrated over to scons, you should be able to compile it now.

**Comment by Adamek-K** [comment]
Considering shipping scons-local with the engine, so you don't need to install scons externally with pip, but that may be a bit too much for the project

**Comment by BoogeyMan24** [comment]
> hey, thanks yeah i have been having some issues compiling it too. it worked fine before, but ever since @BoogeyMan24 introduced the libs and include into the project it has been failing to compile. i am working on getting a fix ASAP. thanks for your interest in the project :)

FORTNIE BATTLESS PASS ASDHAFUBS FJASFOJSNDGSAASAS PASS AMONGUYS

**Comment by Adamek-K** [comment]
closing this, scons is working well and I think scons-local is kind of unecessary, at least for now

**Comment by formerlybased** [comment]
changed to cmake
