### ISSUE TITLE
Support for Windows development

### ISSUE THREAD

**Issue by drakemj** [Adamek-K/feather-engine#10]
As far as I can tell, this doesn't run out of the box on Windows. Maybe add some support for Windows developers?

![image](https://user-images.githubusercontent.com/62521534/193434766-ed30a9dc-249d-445c-93ec-fc36c678357f.png)

Runs into an error here  (\include\SDL2\SDL_config.h) after running scons. I don't really know why this is here or anything but I will mess around and see if I can get it to somehow compile

**Comment by Adamek-K** [comment]
Hi, thanks for telling me. I've had some other people report the same issue, and when I tested it on my windows machine I got the same error. I am working on fixing it ASAP - as far as I can tell it is an issue with SDL not wanting to work with microsoft visual compiler for whatever reason.

**Comment by Adamek-K** [comment]
@drakemj see #11 . I have added window support, tell me if you have any issues remaining.

**Comment by Adamek-K** [comment]
@drakemj can you confirm that it works for you now so I can close this issue?

**Comment by Adamek-K** [comment]
As far as I can tell this works now, closing issue
