### ISSUE TITLE
Redundancy in entity.cpp

### ISSUE THREAD

**Issue by drakemj** [Adamek-K/feather-engine#24]
![image](https://user-images.githubusercontent.com/62521534/193994500-2ab18b6b-b90c-4f6b-937b-b4c7c2ce4756.png)

Thinking that we just have the first function create two vectors and call the second using those

**Comment by Adamek-K** [comment]
That sounds good, this redundancy exists because the original Create() was written before Vectors existed in the engine, and the second one was added when Vectors were added, so the first one mainly exists due to historical happenstance. Go ahead and implement your idea in a PR if you wish.

**Comment by Adamek-K** [comment]
fixed in #25
