### ISSUE TITLE
More object mechanics/ touch up mouse_game.cpp

### ISSUE THREAD

**Issue by drakemj** [Adamek-K/feather-engine#30]
I think that as of now, mouse_game.cpp makes the physics feel wonky. Going to try and add in a clone function for RigidEntity and also adjust the physics of that a bit

**Comment by Adamek-K** [comment]
Alright, if you do add a clone function to RigidEntity I recommend you try to port it to the Entity class as well

**Comment by drakemj** [comment]
Just read this, will port it to Entity and update the PR/make a new one

**Comment by Adamek-K** [comment]
Completed in #31
