### ISSUE TITLE
Font not loading correctly in game anymore

### ISSUE THREAD

**Issue by drakemj** [Adamek-K/feather-engine#35]
Probably has something to do with moving the build to a separate directory? Thought I tested this, so maybe it's something else... but seems like it has to do with not being able to reach the .ttf file.

**Comment by Adamek-K** [comment]
Hi, I know why this is happening. When the executable is compiled into build/, the font is not moved with it, causing it to not be able to find the font. When building, the font should be moved into the feather/ directory of build/. There is a similar problem with assets failing to load, and needing to be manually moved into an assets folder in the build directory.

**Comment by Adamek-K** [comment]
Fixed in #36
